create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  category text not null,
  slot_key text not null,
  points integer not null check (points in (1, 2, 3)),
  question text not null unique,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_index integer not null check (correct_index between 0 and 3),
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists idx_questions_slot_key on public.questions(slot_key);
create index if not exists idx_questions_category on public.questions(category);
create index if not exists idx_questions_points on public.questions(points);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.questions to anon, authenticated;
grant select, insert, update, delete on public.questions to service_role;
grant usage, select on sequence public.questions_id_seq to service_role;

alter table public.questions enable row level security;

drop policy if exists "Questions are readable by everyone" on public.questions;
create policy "Questions are readable by everyone"
on public.questions
for select
using (true);
